Delete _datasets/pa-legislative-districts-us-congressional-2011.md
opendataphilly/opendataphilly-jkan pull request #202
Opened 2024-04-27 20:38 UTC by rcheetham

#201

2024-04-28 17:58 UTC, BryanQuigley requested changes
The aws links still seem to work for me.

2024-04-29 00:52 UTC, rcheetham commented
@BryanQuigley this is from the 2011 redistricting cycle and there is no web presence or links to the data. The legislative districts are no longer valid, even if they can be accessed.

2024-04-29 00:53 UTC, BryanQuigley approved these changes

2024-04-29 00:53 UTC, BryanQuigley approved these changes

2024-04-29 00:53 UTC, merged